### ISSUE TITLE
Starting the container changes folders owners

### ISSUE THREAD

**Issue by paolobasso99** [BytemarkHosting/docker-webdav#24]
Hi,
When I start this docker container the owner of the folders shared using volumes in my Ubuntu server changes to `82:82`. Is this a wanted behavior?  

I am using this `docker-compose.yml` :
```
mediabox-webdav:
    image: bytemark/webdav
    container_name: mediabox-webdav
    environment:
      - USERNAME=${WEBDAV_USERNAME}
      - PASSWORD=${WEBDAV_PASSWORD}
    volumes:
      - /mediabox:/var/lib/dav/data/mediabox
      - /downloads:/var/lib/dav/data/downloads
    restart: unless-stopped
```
The owner of both `/mediabox` and `/downloads` becomes `82:82`,is there a way to avoid this and keep the original owner?
