### ISSUE TITLE
Unable to delete via client

### ISSUE THREAD

**Issue by psyciknz** [BytemarkHosting/docker-webdav#3]
I can start the container, and in the container the default user has access to write and delete to the location exposed to web dav.  I assume that means that the container has the permissions it requires?

But when I connect with a client, either windows mapped drive, or ios, they can both read the contents of the webdav folder, but any type of delete will gather a 403 error.

I've tried playing with the dav.conf to add limit, and limitexcept, but no joy.

The error in the docker log is as follows:
```
192.168.10.211 - - [07/Jan/2019:22:10:50 +0000] "DELETE /MyPDF.pdf HTTP/1.1" 401 381 "-" "Microsoft-WebDAV-MiniRedir/6.1.7601"

[Mon Jan 07 22:10:50.672112 2019] [dav:error] [pid 11:tid 1989401928] [client 192.168.10.211:54185] Could not DELETE /MyPDF.pdf.  [403, #0]
```

Docker Compose as follows:
```
webdav:
    container_name: webdav
    hostname: webdav
    environment:
      - TZ=Pacific/Auckland
      - AUTH_TYPE=Digest
      - USERNAME=user
      - PASSWORD=password
    image: bytemark/webdav
    ports:
      - "8085:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /media/pdfs:/var/lib/dav/data

```
